apiVersion: v1
kind: Service
metadata:
  name: mappa-quartiere
  labels:
    app: mappa-quartiere
spec:
  ports:
  - name: client
    port: 3000
  - name: server
    port: 4000
  selector:
    app: mappa-quartiere
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mappa-quartiere-deployment
spec:
  replicas: 1
  strategy:
      type: Recreate
  template:
    metadata:
      labels:
        app: mappa-quartiere
    spec:
      containers:
      - name: mappa-quartiere
        image: nexus.daf.teamdigitale.it/mappa-quartiere:1.0.0-SNAPSHOT
        imagePullPolicy: Always
        lifecycle:
          postStart:
            exec:
             command: ["/bin/sh", "-c", "cat /etc/extra_hosts >> /etc/hosts"]
        ports:
        - name: client
          containerPort: 3000
        - name: server
          containerPort: 4000
        securityContext:
          privileged: true
          runAsUser: 0
        volumeMounts:
        - name: hosts
          mountPath: /etc/extra_hosts
      imagePullSecrets:
      - name: regsecret
      volumes:
      - name: hosts
        hostPath:
          path: /etc/hosts